#!/usr/bin/env zsh
source helpers.sh

while getopts ":chlx:d:e:f:m:n:v:s:" option; do
  case $option in
  c)
    collect
    commit
    update_refs
    exit ;;
    
  d)
    sed -i "$2d" "$repo""$3".note
    view $3 "-v1"
    commit
    exit ;;

  e)
    gamma-editor "$repo""$2".note
    exit ;;

  f)
    find "$repo" -not -path '*/.*' -type f -print0 | xargs -0 grep -i "$2"
    exit ;;

  h)
    help_menu
    exit ;;

  l)
    ls -goh "$repo"
    exit ;;

  n)
    new "$2" "$3"
    exit ;;

  m)
    mv "$repo""$2".note "$repo""$3".note
    commit
    update_refs
    exit ;;

  v)
    view $2 $1
    exit ;;

  s)
    find "$repo" -name "*$2*.note" -printf "%f\n"
    exit ;;

  x)
    rm "$repo""$2".note
    commit
    update_refs
    exit ;;

  \?)
    help_menu
    exit ;;
  esac
done

if [ $OPTIND -eq 1 ]
 then
  case "$1" in
  	"copy")
      copy $2 $3
      exit ;;

    "sync")
      sync
      exit ;;

    "status")
      status
      exit ;;

    "")
      ls "$repo";
      exit ;;

    *)
      new "$1" "$2"
      exit ;;
  esac
fi
