#!/bin/bash
printf "Note management commands:\n\n"

echo "-c                    collects all .note files to /home/ric/notes"
echo "-e [name]             edits a note"
echo "-e [query]            finds notes containing [query]"
echo "-h                    shows this help menu"
echo "-l                    lists all notes"
echo "-m [current] [new]    renames [current] to [new]"
echo "-n [name] [content]   creates a new note"
echo "-p [name]             prints a note to the terminal"
echo "-s [filter]           search for notes that match *[filter]*.note"
echo "-x [name]             deletes a note"
