#!/usr/bin/env zsh
source helpers.sh

while getopts ":chlx:d:e:f:m:n:v:s:" option; do
  case $option in
  c)
    collect
    commit
    update_refs
    exit ;;
    
  d)
    sed -i "$2d" /home/ric/notes-repo/"$3".note
    view $3
    commit
    exit ;;

  e)
    gamma-editor /home/ric/notes-repo/"$2".note
    exit ;;

  f)
    find /home/ric/notes-repo -type f -print0 | xargs -0 grep -i "$2"
    exit ;;

  h)
    help_menu
    exit ;;

  l)
    ls -goh /home/ric/notes-repo
    exit ;;

  n)
    new "$2" "$3"
    exit ;;

  m)
    mv /home/ric/notes-repo/"$2".note /home/ric/notes-repo/"$3".note
    commit
    update_refs
    exit ;;

  v)
    view $2
    exit ;;

  s)
    find /home/ric/notes-repo -name "*$2*.note" -printf "%f\n"
    exit ;;

  x)
    rm /home/ric/notes-repo/"$2".note
    commit
    update_refs
    exit ;;

  \?)
    help_menu
    exit ;;
  esac
done

if [ $OPTIND -eq 1 ]
 then
  case "$1" in
  	"copy")
      copy $2 $3
      exit ;;

    "sync")
      sync
      exit ;;

    "status")
      status
      exit ;;

    *)
      ls /home/ric/notes-repo;
      exit ;;
  esac
fi
